#!/usr/bin/env ruby
# frozen_string_literal: true

require 'find_circle_yml'

provided_configurations = [
  FindCircleYml::Bitbucket::Configuration.new(ENV),
  FindCircleYml::GitHub::Configuration.new(ENV)
].select(&:provided?)

if provided_configurations.empty?
  STDERR.puts 'Provide a Bitbucket or GitHub configuration'
  exit 1
end

provided_configurations.each do |configuration|
  if configuration.valid?
    service = configuration.service
    service.repositories.each do |repository|
      configuration_files = service.configuration_files(repository)
      puts "#{repository.url} is using default (v1) config" unless configuration_files.any?{ |c| c.present }
      configuration_files.select(&:present).each{ |c| puts "#{repository.url}/blob/master/#{c.path} is not using v2 config" unless c.version == 2 }
    end
  else
    STDERR.puts configuration.error_message
    exit 1
  end
end
